title: Songs With Handclaps
highlighter: pygments
amazonAssociateId: songwithhand-20
itunesAffiliateId: 1000l3KA
permalink: none

defaults:
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
